#!/bin/python3
import json

# Invalid JSON data
data = "{invalid_json_key: 'value'}"

def check_validity(string_json): # create new function
    try:
        json.loads(string_json) # if the data loads successfully, then the function value is true
        return True
    except ValueError: # if a value error occurs when laoding data, then the function value is false
        return False

if check_validity(data): # if function was true, load data into "json_data"
    json_data = json.loads(data)
else:
    print("Sorry. We could not load the data.") # otherwise, print error statement
